# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "materials", :force => true do |t|
    t.column "supplier_id", :integer
    t.column "name",        :string
    t.column "price",       :float
  end

  create_table "order_positions", :force => true do |t|
    t.column "order_id",         :integer
    t.column "receiver_email",   :string
    t.column "material_id",      :integer
    t.column "debt_for_orderer", :float
    t.column "material_price",   :float
  end

  create_table "orders", :force => true do |t|
    t.column "delivery_date", :date
    t.column "supplier_id",   :integer
    t.column "orderer",       :string
    t.column "comments",      :text
    t.column "state",         :integer, :default => 4, :null => false
  end

  create_table "suppliers", :force => true do |t|
    t.column "name",   :string
    t.column "email",  :string
    t.column "phones", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
